tdx-signed-dmverity: fix build issue on imx8m devices
iMX8M devices doesn't use imx-boot anymore, so the do_image_bootfs task
cannot depend on it anymore.

Fixes the following build error:

ERROR: imx-boot-1.0-r0 do_compile: Generating the bootloader container
via imx-boot is no longer supported; please review your setting of
UBOOT_PROVIDES_BOOT_CONTAINER.

Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>