tdx-reference-ramdisk-image: fix undefined variable case
0e08b8d3ed: tdx-reference-ramdisk-image.bb: fix do_rootfs dependency definition
introduced a regression when the DM_VERITY_IMAGE_TYPE variable is
not defined, typically when dm-verity is not enabled.

In this case, the statement:
@d.getVar('DM_VERITY_IMAGE_TYPE').replace('-', '_')
errors with this message:
AttributeError: 'NoneType' object has no attribute 'replace'

tdx-reference-ramdisk-image.bb is only relevant when the "tdxref-signed"
class is inherited, but it is parsed in any case.

Add "or ''" to the expression, to make sure the result
is always a string, on which the replace() operator can be applied.

Tested in both cases: DM_VERITY_IMAGE_TYPE defined and not defined.

Signed-off-by: Michael Opdenacker <michael.opdenacker@rootcommit.com>