u-boot: fix build error on i.MX8M when CA flag is unset
When secure boot is enabled but the CA flag is not set, the variables
TDX_IMX_HAB_CST_CSF_CERT and TDX_IMX_HAB_CST_IMG_CERT are not defined,
so their contents don't need to be verified.

This avoids the following build error:

ERROR: u-boot-toradex-1_2024.07-r0 do_uboot_assemble_fitimage: Could not
find file '${f}' (required for HAB)

Fixes #103

Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>